- name: add locales
  shell: locale-gen {{ item }}
  register: locale_gen_out
  changed_when: not "up-to-date" in locale_gen_out.stdout
  with_items:
    - en_GB.UTF-8
    - en_GB
    - nl_NL.UTF-8
    - nl_NL
    - nl_BE.UTF-8
    - nl_BE
    - fr_BE.UTF-8
    - fr_BE
