- name: install webserver
  apt: pkg={{ item }} state=present
  with_items:
    - apache2
    - php5
    - php5-mysql
    - php5-gd
    - php5-dev
    - php5-curl
    - php-apc
    - php5-cli
    - php-services-json

- name: Disable default site
  action: command a2dissite 000-default

- name: enable required mods
  action: command a2enmod rewrite

- name: Add server name to apache
  lineinfile: dest=/etc/apache2/conf.d/servername.conf regexp="^Servername " line="Servername localhost" create=yes
